core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path('', views.index, name="homepage"),
    path('checkout/', views.CheckoutView.as_view(), name="checkout"),
    path('order-summary/', views.OrderSummaryView.as_view(), name="order-summary"),
    path('product/<slug>/', views.ItemDetailView.as_view(), name="product"),
    path('add-to-cart/<slug>/', views.add_to_cart, name="add-to-cart"),
    path('add-coupon/', views.AddCouponView.as_view(), name="add-coupon"),
    path('remove-from-cart/<slug>/',
         views.remove_from_cart, name="remove-from-cart"),
    path('remove-item-from-cart/<slug>/',
         views.remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name="payment"),
    path("request-refund/", views.RequestRefundView.as_view(), name="request-refund")
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('pybo/', include('pybo.urls', namespace='pybo')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'
urlpatterns = [
    path('', base_views.index, name="index"),
    path('<int:questionId>/', base_views.detail, name="detail"),
    path('answer/create/<int:questionId>/',
         answer_views.answerCreate, name="answer_create"),
    path("question/create/", question_views.questionCreate, name="question_create"),
    path("question/modify/<int:question_id>/",
         question_views.questionModify, name="question_modify"),
    path('question/delete/<int:questionId>/',
         question_views.questionDelete, name="question_delete"),
    path('answer/modify/<int:answerId>/',
         answer_views.answerModify, name="answer_modify"),
    path('answer/delete/<int:answerId>/',
         answer_views.answerDelete, name="answer_delete"),
    path('comment/create/question/<int:questionId>/',
         comment_views.commentCreateQuestion, name="comment_create_question"),
    path('comment/modify/question/<int:commentId>/',
         comment_views.commentModifyQuestion, name="comment_modify_question"),
    path('comment/delete/question/<int:commentId>/',
         comment_views.commentDeleteQuestion, name="comment_delete_question"),
    path('comment/create/answer/<int:answerId>/',
         comment_views.commentCreateAnswer, name='comment_create_answer'),
    path('comment/modify/answer/<int:commentId>/',
         comment_views.commentModifyAnswer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:commentId>/',
         comment_views.commentDeleteAnswer, name='comment_delete_answer'),
    path('vote/question/<int:questionId>/',
         vote_views.voteQuestion, name="vote_question"),
    path('vote/answer/<int:answerId>/',
         vote_views.voteAnswer, name="vote_answer"),
]

pybo/models.py
from django.db import models
from django.conf import settings


class Question(models.Model):
    # 제목처럼 글자수의 길이가 제한된 텍스트는 CharField를 사용해야 한다.
    subject = models.CharField(max_length=200)
    content = models.TextField()
    # 내용(content)처럼 글자수를 제한할 수 없는 텍스트는 위처럼 TextField를 사용해야 한다.
    createDate = models.DateTimeField()
    # 작성일시처럼 날짜와 시간에 관계된 속성은 DateTimeField를 사용해야 한다.
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE, related_name="author_question")
    modifyDate = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="voter_question")
    # 이렇게 하면 이제 특정 사용자가 작성한 질문을 얻기 위해서는 current_user.author_question.all() 처럼 사용할 수 있다. 마찬가지로 특정 사용자가 투표한 질문을 얻기 위해서는 current_user.voter_question.all() 처럼 사용할 수 있다. (current_user는 특정 사용자를 의미한다.)

    def __str__(self):
        return self.subject
    # ※ 모델에 메서드가 추가될 경우에는 makemigrations와 migrate 를 수행할 필요는 없다. migrate가 필요한 경우는 모델의 속성이 변경되었을 때뿐이다.


class Answer(models.Model):
    # 기존 모델을 속성으로 가져갈 경우 ForeignKey를 이용해야 한다. ForeignKey는 다른 모델과의 연결을 의미한다. on_delete=models.CASCADE의 의미는 이 답변과 연결된 질문(Question)이 삭제될 경우 답변(Answer)도 함께 삭제된다는 의미이다.
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="author_answer")
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # Question과 Answer는 서로 연결되어 있기 때문에 answer_set을 사용하면 질문과 연결된 답변을 가져올 수 있다. Answer모델에서 ForignKey로 Question을 연결해 주었기 때문에 answer_set이 가능해진 것이다.
    content = models.TextField()
    createDate = models.DateTimeField()
    modifyDate = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="voter_answer")
    # null=True의 의미는 modify_date를 데이터베이스에 저장할때 null이 허용된다는 의미이다. blank=True의 의미는 입력 폼 데이터 체크시(form.is_valid()) 값이 없어도 오류를 내지 않는다는 의미이다. 즉, null=True, blank=True을 사용하면 어떤 조건으로든 값을 비워둘수 있음을 의미한다. 수정일시는 수정이 발생할 경우에만 생성되는 데이터이므로 null=True, blank=True 속성을 지정하였다.

# 이제 작성한 모델을 이용하여 테이블들을 생성해 보자. 테이블 생성을 위해 가장 먼저 해야 할 일은 pybo앱을 config/settings.py 파일의 INSTALLED_APPS 항목에 추가하는 일이다.


class Comment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    createDate = models.DateTimeField()
    modifyDate = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(
        Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(
        Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.core.paginator import Paginator
# from django.http import HttpResponse
from ..models import Question, Answer, Comment
from ..forms import QuestionForm, AnswerForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.


@login_required(login_url="account_login")
def answerCreate(request, questionId):
    question = get_object_or_404(Question, pk=questionId)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.createDate = timezone.now()
            answer.question = question
            answer.author = request.user
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', questionId=question.id), answer.id))
        else:
            messages.warning(request, 'Failed answer submit')
            return render(request, "pybo/question_detail.html", {'question': question, 'form': form})
    else:
        form = AnswerForm()
        context = {'question': question, 'form': form}
        return render(request, "pybo/question_detail.html", context)


@login_required(login_url='account_login')
def answerModify(request, answerId):
    answer = get_object_or_404(Answer, pk=answerId)
    if request.user != answer.author:
        messages.warning(request, 'Not authorized to modify')
        return redirect('pybo:detail', questionId=answer.question.id)
    else:
        if request.method == "GET":
            form = AnswerForm(instance=answer)
            context = {'answer': answer, 'form': form}
            return render(request, 'pybo/answer_form.html', context)
        else:
            form = AnswerForm(request.POST, instance=answer)
            if form.is_valid():
                answer = form.save(commit=False)
                answer.author = request.user
                answer.modifyDate = timezone.now()
                answer.save()
                return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', questionId=answer.question.id), answer.id))
            else:
                context = {'answer': answer, 'form': form}
                return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='account_login')
def answerDelete(request, answerId):
    answer = get_object_or_404(Answer, pk=answerId)
    if request.user != answer.author:
        messages.warning(request, 'Not authorized to delete')
    else:
        answer.delete()
        messages.info(request, 'Successfully deleted your answer.')
    return redirect('pybo:detail', questionId=answer.question.id)

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
# from django.http import HttpResponse
from ..models import Question, Answer, Comment
from ..forms import QuestionForm, AnswerForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q, Count
# Create your views here.


def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if so == "recommend":
        questionList = Question.objects.annotate(
            numVoter=Count('voter')).order_by('-numVoter', '-createDate')
    elif so == "popular":
        questionList = Question.objects.annotate(numAnswer=Count(
            'answer')).order_by('-numAnswer', '-createDate')
    else:
        questionList = Question.objects.order_by('-createDate')
    # page = request.GET.get('page', '1') 은 다음처럼 GET방식으로 요청한 URL에서 page의 값을 가져올때 사용한다. http://localhost:8000/pybo/?page=1
    # 만약 http://localhost:8000/pybo/ 처럼 page값이 없을 경우에는 디폴트로 1이라는 값을 설정한다.

    if kw:
        questionList = questionList.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw) |  # 답변 글쓴이검색
            Q(answer__content__icontains=kw)
        ).distinct()

    paginator = Paginator(questionList, 10)
    pageObj = paginator.get_page(page)
    context = {'questionList': pageObj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)
    # A context is a variable name -> variable value mapping that is passed to a template. Context processors let you specify a number of variables that get set in each context automatically – without you having to specify the variables in each render() call.


def detail(request, questionId):
    # question = Question.objects.get(id=questionId)
    question = get_object_or_404(Question, pk=questionId)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.core.paginator import Paginator
# from django.http import HttpResponse
from ..models import Question, Answer, Comment
from ..forms import QuestionForm, AnswerForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.


@login_required(login_url='account_login')
def commentCreateQuestion(request, questionId):
    question = get_object_or_404(Question, pk=questionId)
    if request.method == "GET":
        form = CommentForm()
        context = {'form': form}
        return render(request, 'pybo/comment_form.html', context)
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.createDate = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', questionId=comment.question.id), comment.id))
        else:
            return render(request, 'pybo/comment_form.html', {'form': form})


@login_required(login_url='account_login')
def commentModifyQuestion(request, commentId):
    comment = get_object_or_404(Comment, pk=commentId)
    if request.user != comment.author:
        messages.warning(request, "Not authorized to modify")
        return redirect('pybo:detail', questionId=comment.question.id)
    else:
        if request.method == "GET":
            form = CommentForm(instance=comment)
            context = {'form': form}
            return render(request, 'pybo/comment_form.html', context)
        else:
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = request.user
                comment.modifyDate = timezone.now()
                comment.save()
                return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', questionId=comment.question.id), comment.id))
            else:
                context = {'form': form}
                return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='account_login')
def commentDeleteQuestion(request, commentId):
    comment = get_object_or_404(Comment, pk=commentId)
    if request.user != comment.author:
        messages.warning(request, 'Not authorized to delete')
        return redirect('pybo:detail', questionId=comment.question.id)
    else:
        comment.delete()
        messages.info(request, 'Successfully deleted your comment.')

        return redirect('pybo:detail', questionId=comment.question.id)


@login_required(login_url='account_login')
def commentCreateAnswer(request, answerId):
    answer = get_object_or_404(Answer, pk=answerId)
    if request.method == "GET":
        form = CommentForm()
        context = {'form': form}
        return render(request, 'pybo/comment_form.html', context)
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.createDate = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', questionId=comment.answer.question.id), comment.id))
        else:
            return render(request, 'pybo/comment_form.html', {'form': form})


@login_required(login_url='account_login')
def commentModifyAnswer(request, commentId):
    comment = get_object_or_404(Comment, pk=commentId)
    if request.user != comment.author:
        messages.warning(request, "Not authorized to modify")
        return redirect('pybo:detail', questionId=comment.answer.question.id)
    else:
        if request.method == "GET":
            form = CommentForm(instance=comment)
            context = {'form': form}
            return render(request, 'pybo/comment_form.html', context)
        else:
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = request.user
                comment.modifyDate = timezone.now()
                comment.save()
                return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', questionId=comment.answer.question.id), comment.id))
            else:
                context = {'form': form}
                return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='account_login')
def commentDeleteAnswer(request, commentId):
    comment = get_object_or_404(Comment, pk=commentId)
    if request.user != comment.author:
        messages.warning(request, 'Not authorized to delete')
        return redirect('pybo:detail', questionId=comment.answer.question.id)
    else:
        comment.delete()
        messages.info(request, 'Successfully deleted your comment.')
        return redirect('pybo:detail', questionId=comment.answer.question.id)

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from ..models import Question, Answer

@login_required(login_url='account_login')
def voteQuestion(request, questionId):
    question = get_object_or_404(Question, pk=questionId)
    if request.user == question.author:
        messages.warning(request, "You can't 'Like' your own post")
    else:
        question.voter.add(request.user)
        messages.success(request, f"Like it 👍🏻 to #post [{question.subject}]")
    return redirect('pybo:detail', questionId=question.id)

    # Question 모델의 vorter는 여러사람을 추가할 수 있는 ManyToManyField이므로 question.voter.add(request.user) 처럼 add 함수를 사용하여 추천인을 추가해야 한다. 
    # ※ 동일한 사용자가 동일한 질문을 여러번 추천하더라도 추천수가 증가하지는 않는다. ManyToManyField를 사용하더라도 중복은 허락되지 않는다.

@login_required(login_url='account_login')
def voteAnswer(request, answerId):
    answer = get_object_or_404(Answer, pk=answerId)
    if request.user == answer.author:
        messages.warning(request, "You can't 'Like' your own post")
    else:
        answer.voter.add(request.user)
        messages.success(request, f"Like it 👍🏻 to #{answer.author.username}'s answer on #post [{answer.question.subject}]")
    return redirect('pybo:detail', questionId=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">Answer Content</label>
            <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn btn-mdb-color">Submit Answer</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
btn-mdb-color{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <h5 class="border-bottom pb-2">Add Comment</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="form-group">
      <label for="content">Comment Content</label>
      <textarea class="form-control" name="content" id="content" rows="3">
{{ form.content.value | default_if_none:'' }}</textarea
      >
    </div>
    <button type="submit" class="btn btn-mdb-color">Save</button>
  </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %} 
{% load pybo_filter %} 
{% block extra_head %}
<style type="text/css">
  .commentContent p {
    margin-top: 0;
    margin-bottom: 0 !important;
  }
</style>
{% endblock extra_head %} 
{% block content %}

<div class="container my-3">
  <h2 class="border-bottom py-2" style="display: flex; justify-content: space-between; align-items:center;">{{question.subject}}
    <div
    class="btn btn-success"
    style="
      border: 4px solid rgb(205, 219, 139);
      cursor: none;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    "
  >
    <span>{{ question.voter.count }}</span>
    <a 
      href="#"
      data-uri="{% url 'pybo:vote_question' question.id %}"
      class="recommend {% if not user.is_authenticated %}disabled{% endif %}"
      style="color: whitesmoke;"
      ><i class="fas fa-thumbs-up fa-2x"></i
    ></a>
  </div>
  </h2>
  <div class="row my-3">
    <div class="col-12">
      <div class="card" style="background-color: #f7f7e9;">
        <div class="card-body">
          <div class="card-text">
            {{question.content|mark}}
          </div>
          <div class="row justify-content-end p-2">
            {% if question.modifyDate %}
            <div class="badge-light badge p-2 text-left mx-2 mb-2">
              <div class="mb-2">Edited at</div>
              <div>{{ question.modifyDate }}</div>
            </div>
            {% endif %}
            <div class="badge badge-dark p-2 text-left mb-2 mx-2">
              <div class="mb-2">{{ question.author.username }}</div>
              <div>{{question.createDate}}</div>
            </div>
          </div>
          {% if request.user == question.author %}
          <div class="mt-3">
            <a
              href="{% url 'pybo:question_modify' question.id %}"
              class="btn btn-sm btn-elegant"
              style="border: none;"
              >Edit</a
            >
            <a
              href="#"
              class="delete btn btn-sm btn-elegant ml-2"
              style="border: none;"
              data-uri="{% url 'pybo:question_delete' question.id %}"
              >Delete</a
            >
          </div>
          {% endif %}
        </div>
        {% if question.comment_set.count > 0 %}
        <div class="m-3">
          {% for comment in question.comment_set.all %}
          <a name="comment_{{ comment.id }}"></a>
          <div
            class="p-2 my-1 text-left"
            style="
              background-color: #cccec7;
              border-radius: 0 10px 10px 10px;
              width: 100%;
              display: flex;
              justify-content: space-between;
            "
          >
            <span class="small commentContent"
              >{{ comment.content|mark }}
            </span>
            <span class="small text-muted commentContent">
              @ {{ comment.author }} / {{ comment.createDate }}
            </span>
          </div>
          {% if request.user == comment.author %}
          <div class="d-flex justify-content-end">
            <div>
              <a
                href="{% url 'pybo:comment_modify_question' comment.id %}"
                class="small btn btn-sm btn-elegant"
                style="
                  background-color: rgb(216, 223, 182);
                  border: none;
                  padding: 0px 0.5em;
                "
                ><small>Edit</small></a
              >
              <a
                href="#"
                class="small delete btn btn-sm btn-elegant ml-1"
                style="
                  background-color: rgb(216, 223, 182);
                  border: none;
                  padding: 0px 0.5em;
                "
                data-uri="{% url 'pybo:comment_delete_question' comment.id %}"
                ><small>Delete</small></a
              >
            </div>
          </div>
          {% endif %} {% endfor %}
        </div>
        {% endif %} {% if user.is_authenticated %}
        <div>
          <a
            href="{% url 'pybo:comment_create_question' question.id %}"
            class="m-3 btn btn-sm btn-mdb-color"
            style="background-color: rgb(216, 223, 182); border: none;"
            ><small>Add Comment</small></a
          >
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <h5 class="border-bottom my-3 py-2">Total answer: {{question.answer_set.count}}</h5>
  {% for answer in question.answer_set.all %}
  <a name="answer_{{answer.id}}"></a>
  <div class="mt-4 mb-0" style="display: flex; justify-content: flex-end;">
    <div
    class="btn btn-amber btn-sm"
    style="
      border: 4px solid rgb(250, 219, 126);
      cursor: none;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    "
  >
    <span>{{ answer.voter.count }}</span>
    <a
      href="#"
      data-uri="{% url 'pybo:vote_answer' answer.id %}"
      class="recommend {% if not user.is_authenticated %}disabled{% endif %}"
      style="color: whitesmoke;"
      ><i class="fas fa-thumbs-up fa-2x"></i
    ></a>
  </div>
  </div>
  <div class="row my-2" style="display: flex; justify-content: space-around;">
    <div class="col-12">
      <div class="card" style="background-color: #f7f7e9;">
        <div class="card-body">
          <div class="card-text">
            {{answer.content|mark}}
          </div>
          <div class="row justify-content-end p-2">
            {% if answer.modifyDate %}
            <div class="badge badge-light p-2 text-left mx-2 mb-2">
              <div class="mb-2">Edited at</div>
              <div>{{ answer.modifyDate }}</div>
            </div>
            {% endif %}
            <div class="badge badge-dark p-2 text-left mb-2 mx-2">
              <div class="mb-2">{{ answer.author.username }}</div>
              <div>{{answer.createDate}}</div>
            </div>
          </div>
          {% if request.user == answer.author %}
          <div class="mt-3">
            <a
              href="{% url 'pybo:answer_modify' answer.id %}"
              class="btn btn-sm btn-elegant"
              >Edit</a
            >
            <a
              href="#"
              class="delete btn btn-sm btn-elegant ml-2"
              style="border: none;"
              data-uri="{% url 'pybo:answer_delete' answer.id %}"
              >Delete</a
            >
          </div>
          {% endif %}
        </div>
        {% if answer.comment_set.count > 0 %}
        <div class="m-3">
          {% for comment in answer.comment_set.all %}
          <a name="comment_{{ comment.id }}"></a>
          <div
            class="p-2 my-1 text-left"
            style="
              background-color: #cccec7;
              border-radius: 0 10px 10px 10px;
              width: 100%;
              display: flex;
              justify-content: space-between;
            "
          >
            <span class="commentContent small"
              >{{ comment.content|mark }}
            </span>
            <span class="small text-muted commentContent">
              @ {{ comment.author }} / {{ comment.createDate }}
            </span>
          </div>
          {% if request.user == comment.author %}
          <div class="d-flex justify-content-end">
            <div>
              <a
                href="{% url 'pybo:comment_modify_answer' comment.id %}"
                class="small btn btn-sm btn-elegant"
                style="
                  background-color: rgb(216, 223, 182);
                  border: none;
                  padding: 0px 0.5em;
                "
                ><small>Edit</small></a
              >
              <a
                href="#"
                class="small delete btn btn-sm btn-elegant ml-1"
                style="
                  background-color: rgb(216, 223, 182);
                  border: none;
                  padding: 0px 0.5em;
                "
                data-uri="{% url 'pybo:comment_delete_answer' comment.id %}"
                ><small>Delete</small></a
              >
            </div>
          </div>
          {% endif %} {% endfor %}
        </div>
        {% endif %} {% if user.is_authenticated %}
        <div>
          <a
            href="{% url 'pybo:comment_create_answer' answer.id %}"
            class="m-3 btn btn-sm btn-mdb-color"
            style="background-color: rgb(216, 223, 182); border: none;"
            ><small>Add Comment</small></a
          >
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
  <form
    action="{% url 'pybo:answer_create' question.id %}"
    method="post"
    class="my-3"
  >
    {% csrf_token %} {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %} {% if field.errors %}
      <strong>{{field.label}}</strong>
      {{field.errors}} {% endif %} {% endfor %}
    </div>
    {% endif %}
    <div class="form-group">
      <textarea
        {% if not user.is_authenticated %}disabled{% endif %}
        name="content"
        id="answerContent"
        class="form-control"
        rows="10"
        placeholder="Write your answer here ✨"
      ></textarea>
    </div>
    {% if user.is_authenticated %}<input
      type="submit"
      value="Submit Answer"
      class="btn btn-mdb-color"
    />
    {% else %}
    <a
      href="{% url 'pybo:answer_create' question.id %}"
      class="btn btn-info"
      style="color: white;"
      >Login to Answer</a
    >
    {% endif %}
  </form>
</div>
{% endblock %} {% block script %}
<script type="text/javascript">
  $(document).ready(function () {
    $(".delete").on("click", function () {
      if (confirm("Do you want to delete this post?")) {
        location.href = $(this).data("uri");
      }
    });
    $(".recommend").on("click", function () {
      if (confirm("Do you like this post?")) {
        location.href = $(this).data("uri");
      }
    });
  });
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">Ask Question</h5>
  <form method="POST" class="post-form my-3">
    {% csrf_token %} {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %} {% if field.errors %}
      <strong>{{field.label}}</strong>
      {{field.errors}} {% endif %} {% endfor %}
    </div>
    {% endif %}
    <div class="form-group">
      <label for="subject">Title</label>
      <input
        type="text"
        class="form-control"
        name="subject"
        id="subject"
        value="{{form.subject.value|default_if_none:''}}"
        placeholder="Question Title"
      />
    </div>
    <div class="form-group">
      <label for="content">Content</label>
      <textarea
        name="content"
        class="form-control"
        id="content"
        rows="10"
        placeholder="Question Content"
      >
{{form.content.value|default_if_none:''}}</textarea
      >
    </div>
    <button type="submit" class="btn btn-mdb-color">Submit Question</button>
  </form>
</div>

{% endblock %}