core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path('', views.index, name="homepage"),
    path('checkout/', views.CheckoutView.as_view(), name="checkout"),
    path('order-summary/', views.OrderSummaryView.as_view(), name="order-summary"),
    path('product/<slug>/', views.ItemDetailView.as_view(), name="product"),
    path('add-to-cart/<slug>/', views.add_to_cart, name="add-to-cart"),
    path('add-coupon/', views.AddCouponView.as_view(), name="add-coupon"),
    path('remove-from-cart/<slug>/',
         views.remove_from_cart, name="remove-from-cart"),
    path('remove-item-from-cart/<slug>/',
         views.remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name="payment"),
    path("request-refund/", views.RequestRefundView.as_view(), name="request-refund")
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('pybo/', include('pybo.urls', namespace='pybo')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'
urlpatterns = [
    path('', base_views.index, name="index"),
    path('<int:questionId>/', base_views.detail, name="detail"),
    path('answer/create/<int:questionId>/',
         answer_views.answerCreate, name="answer_create"),
    path("question/create/", question_views.questionCreate, name="question_create"),
    path("question/modify/<int:question_id>/",
         question_views.questionModify, name="question_modify"),
    path('question/delete/<int:questionId>/',
         question_views.questionDelete, name="question_delete"),
    path('answer/modify/<int:answerId>/',
         answer_views.answerModify, name="answer_modify"),
    path('answer/delete/<int:answerId>/',
         answer_views.answerDelete, name="answer_delete"),
    path('comment/create/question/<int:questionId>/',
         comment_views.commentCreateQuestion, name="comment_create_question"),
    path('comment/modify/question/<int:commentId>/',
         comment_views.commentModifyQuestion, name="comment_modify_question"),
    path('comment/delete/question/<int:commentId>/',
         comment_views.commentDeleteQuestion, name="comment_delete_question"),
    path('comment/create/answer/<int:answerId>/',
         comment_views.commentCreateAnswer, name='comment_create_answer'),
    path('comment/modify/answer/<int:commentId>/',
         comment_views.commentModifyAnswer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:commentId>/',
         comment_views.commentDeleteAnswer, name='comment_delete_answer'),
    path('vote/question/<int:questionId>/',
         vote_views.voteQuestion, name="vote_question"),
    path('vote/answer/<int:answerId>/',
         vote_views.voteAnswer, name="vote_answer"),
]

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('Starters', 'Starters'),
    ('Main dishes', 'Main dishes'),
    ('Desserts', 'Desserts'),
    ('Drinks', 'Drinks'),
)

LABEL_CHOICES = (
    ('Vegan', 'Vegan'),
    ('Gluten Free', 'Gluten-free'),
    ('Michelin Starred', 'Michelin-starred'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=30)
    label = models.CharField(choices=LABEL_CHOICES,
                             max_length=30, null=True, blank=True)
    slug = models.SlugField()
    description = models.TextField()
    imgsrc = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    is_ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'Address', related_name="billing_address", on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey(
        'Address', related_name="shipping_address", on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    payment_option = models.CharField(max_length=50, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    # 1. Item added to cart
    # 2. Adding a billing address
    # (Failed checkout)
    # 3. Payment
    # (preprocessing, processing, packaging, etc,.)
    # 4. Being delivered
    # 5. Received
    # 6. Refunds

    def __str__(self):
        return self.user.username

    def get_total_gross(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
            if total < 0:
                total = 0
        return total

    def get_total_quantity(self):
        total_quantity = 0
        for order_item in self.items.all():
            total_quantity += order_item.quantity
        return total_quantity

    def get_total_amount_saved(self):
        total_amount_saved = 0
        for order_item in self.items.all():
            amount_saved = order_item.get_total_item_price()-order_item.get_final_price()
            total_amount_saved += amount_saved
        return total_amount_saved


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default_address = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "Addresses"


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=20)

    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
# from django.http import HttpResponse
from ..models import Question, Answer, Comment
from ..forms import QuestionForm, AnswerForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q, Count
# Create your views here.


def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if so == "recommend":
        questionList = Question.objects.annotate(
            numVoter=Count('voter')).order_by('-numVoter', '-createDate')
    elif so == "popular":
        questionList = Question.objects.annotate(numAnswer=Count(
            'answer')).order_by('-numAnswer', '-createDate')
    else:
        questionList = Question.objects.order_by('-createDate')
    # page = request.GET.get('page', '1') 은 다음처럼 GET방식으로 요청한 URL에서 page의 값을 가져올때 사용한다. http://localhost:8000/pybo/?page=1
    # 만약 http://localhost:8000/pybo/ 처럼 page값이 없을 경우에는 디폴트로 1이라는 값을 설정한다.

    if kw:
        questionList = questionList.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw) |  # 답변 글쓴이검색
            Q(answer__content__icontains=kw)
        ).distinct()

    paginator = Paginator(questionList, 10)
    pageObj = paginator.get_page(page)
    context = {'questionList': pageObj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)
    # A context is a variable name -> variable value mapping that is passed to a template. Context processors let you specify a number of variables that get set in each context automatically – without you having to specify the variables in each render() call.


def detail(request, questionId):
    # question = Question.objects.get(id=questionId)
    question = get_object_or_404(Question, pk=questionId)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/form_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger"
role="alert">
<strong>{{ field.label }}</strong>
    <br>
    {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger"
role="alert">
    <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

templates/home.html
{% extends "base.html" %} 
{% block content %}

<!--Carousel Wrapper-->
<div
  id="carousel-example-1z"
  class="carousel slide carousel-fade pt-4"
  data-ride="carousel"
>
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li
      data-target="#carousel-example-1z"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <div
        class="view"
        style="
          background-image: url(https://images.unsplash.com/photo-1550388342-c75d3a99540d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1208&q=80);
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Foods for Geeks</strong>
            </h1>

            <p>
              <strong>Best & delicious food for programmers</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The best food to increase your coding productivity. Simply
                order online and enjoy the food of the finest restaurants in
                your home.</strong
              >
            </p>

            <a href="#" class="btn btn-outline-white btn-lg"
              >Don't cook&nbsp&nbspJust click&nbsp&nbsp
              <i class="fas fa-utensils"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://images.unsplash.com/photo-1496412705862-e0088f16f791?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Foods for Geeks</strong>
            </h1>

            <p>
              <strong>Best & delicious food for programmers</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The best food to increase your coding productivity. Simply
                order online and enjoy the food of the finest restaurants in
                your home.</strong
              >
            </p>

            <a href="#" class="btn btn-outline-white btn-lg"
              >Don't cook&nbsp&nbspJust click&nbsp&nbsp
              <i class="fas fa-utensils"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://images.unsplash.com/photo-1493770348161-369560ae357d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Foods for Geeks</strong>
            </h1>

            <p>
              <strong>Best & delicious food for programmers</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The best food to increase your coding productivity. Simply
                order online and enjoy the food of the finest restaurants in
                your home.</strong
              >
            </p>

            <a href="#" class="btn btn-outline-white btn-lg"
              >Don't cook&nbsp&nbspJust click&nbsp&nbsp
              <i class="fas fa-utensils"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a
    class="carousel-control-prev"
    href="#carousel-example-1z"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carousel-example-1z"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
  <div class="container">
    <!--Navbar-->
    <nav
      class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5"
    >
      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#basicExampleNav"
        aria-controls="basicExampleNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <div class="navbar-nav mr-auto">
          <a class="sort nav-item {% if sort == "all" %} active {% endif %}" data-filter="all" href="#">
            <span class="nav-link">All
              <span class="sr-only">(current)</span>
            </span>
          </a>
          <a class="sort nav-item {% if sort == "starters" %} active {% endif %}" data-filter="starters" href="#">
            <span class="nav-link">Starters</span>
          </a>
          <a class="sort nav-item {% if sort == "main-dishes" %} active {% endif %}" data-filter="main-dishes" href="#">
            <span class="nav-link">Main dishes</span>
          </a>
          <a class="sort nav-item {% if sort == "desserts" %} active {% endif %}" data-filter="desserts" href="#">
            <span class="nav-link">Desserts</span>
          </a>
          <a class="sort nav-item {% if sort == "drinks" %} active {% endif %}" data-filter="drinks" href="#">
            <span class="nav-link">Drinks</span>
          </a>
        </div>
        <!-- Links -->

        <div class="form-inline float-right">
          <button
              class="btn-floating btn-sm btn-mdb-color"
              type="button"
              id="btnSearch"
              style="border: none;"
            >
              <i class="fas fa-search"></i>
            </button>
          <div class="md-form my-0">
            <input
              class="form-control kw ml-2"
              type="text"
              value="{{ kw|default_if_none:'' }}"
              placeholder="Search"
              aria-label="Search"
            />
          </div>
        </div>
      </div>
      <!-- Collapsible content -->
    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <!--Grid row-->
      <div class="row wow fadeIn">
        {% if page_obj %}
        {% for item in page_obj %}
        <div class="col-lg-3 col-md-6 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card image-->
            <div class="view overlay">
              {% if item.image %}
              <img src="{{ item.image.url }}" class="card-img-top" alt="" />
              {% elif not item.image and item.imgsrc %}
              <img src="{{ item.imgsrc }}" class="card-img-top" alt="" />
              {% else %} 
              {% endif %}
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5> {{ item.get_category_display }} </h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text"
                    >{{ item.title }} 
                    {% if item.discount_price %}
                    <span
                      class="badge badge-pill danger-color-dark text-uppercase"
                    >
                      sale
                    </span>
                    {% endif %} 
                    {% if item.label %}
                    <span class="badge badge-pill bg-dark">
                       {{ item.get_label_display }} 
                    </span>
                    {% endif %}
                  </a>
                </strong>
              </h5>
              <h4 class="font-weight-bold blue-text">
                <strong
                  >$ {% if item.discount_price %} 
                  {{ item.discount_price }} 
                  {% else %} 
                  {{ item.price }} 
                  {% endif %}
                </strong>
              </h4>
            </div>
            <!--Card content-->
          </div>
          <!--Card-->
        </div>
        {% endfor %}
        {% else %}
        <div class="col-12">
          <!--Card-->
          <div class="card">
            <!--Card image-->
            <div class="view overlay">
              <img src="https://images.unsplash.com/photo-1531928351158-2f736078e0a1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" class="card-img-top" alt="" />
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <h4 class="font-weight-bold dark-grey-text">
                No matching results found
              </h4>
            </div>
            <!--Card content-->
          </div>
          <!--Card-->
        </div>
        {% endif %}
      </div>
      <!--Grid row-->
    </section>
    <!--Section: Products v.3-->
    <!--Pagination-->
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            data-page="{{ page_obj.previous_page_number }}"
            href="#"
            aria-label="Previous"
          >
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %} 
        {% for pageNumber in page_obj.paginator.page_range %} 
        {% if pageNumber >= page_obj.number|add:-5 and pageNumber <= page_obj.number|add:5 %} 
        {% if pageNumber == page_obj.number %}
        <li class="page-item active">
          <a class="page-link" data-page="{{ pageNumber }}" href="#"
            >{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" data-page="{{ pageNumber }}" href="#"
            >{{ pageNumber }}
          </a>
        </li>
        {% endif %} 
        {% endif %} 
        {% endfor %} 
        {% if page_obj.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            data-page="{{ page_obj.next_page_number }}"
            href="#"
            aria-label="Next"
          >
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</main>
<!--Main layout-->

<form id="searchForm" method="get" action="{% url 'core:homepage' %}">
  <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}" />
  <input type="hidden" id="page" name="page" value="{{ page }}" />
  <input type="hidden" name="sort" id="sort" value="{{ sort }}" />
</form>

{% endblock content %} 
{% block script %}
<script type="text/javascript">
  $(document).ready(function () {
    $(".page-link").on("click", function () {
      $("#page").val($(this).data("page"));
      $("#searchForm").submit();
    });

    $("#btnSearch").on("click", function () {
      $("#kw").val($(".kw").val());
      $("#page").val(1); // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
      $("#searchForm").submit();
    });

    $(".kw").on("keypress", function(e) {
      if(e.which == 13) {
        $("#kw").val($(".kw").val());
        $("#page").val(1); 
        $("#searchForm").submit();
      }
    });

    $(".sort").on("click", function() {
      $("#sort").val($(this).data("filter"));
      $("#page").val(1);
      $("#searchForm").submit();
    });
  });
</script>
{% endblock script %}

templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% for item in items %} {{ item }} {% endfor %} {% endblock content %}

templates/navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
<nav
  class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar"
>
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'core:homepage' %}">
      <strong class="blue-text">FoodsForGeeks</strong>
    </a>
    <!-- Collapse -->
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link waves-effect" href="{% url 'core:homepage' %}"
            >Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:checkout' %}"
            >Checkout</a
          >
        </li> -->
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link waves-effect">
            <span class="badge blue z-depth-1 mr-1"> Welcome ! </span>
            <span class="clearfix d-none d-sm-inline-block">
              {{ user.username}}
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a
            href="{% url 'core:order-summary' %}"
            class="nav-link waves-effect"
          >
            <span class="badge red z-depth-1 mr-1">
              {{ request.user|cart_item_count }}</span
            >
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <i class="fas fa-sign-out-alt"></i>
            <span class="clearfix d-none d-sm-inline-block"> Sign Out </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <i class="fas fa-sign-in-alt"></i>
            <span class="clearfix d-none d-sm-inline-block"> Sign In </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <i class="fas fa-user-plus"></i>
            <span class="clearfix d-none d-sm-inline-block"> Sign Up </span>
          </a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'pybo:index' %}">
            <span class="badge btn-green z-depth-1 mx-1">
              Any question?
            </span>
            <span class="clearfix d-none d-sm-inline-block"> Q & A </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->